import Head from 'next/head'
import { useAuth0 } from "@auth0/auth0-react";

const LoginButton = () => {
  const { loginWithRedirect } = useAuth0();

  return <button onClick={() => loginWithRedirect()}>Log In</button>;
};


const LogoutButton = () => {
  const { logout } = useAuth0();

  return (
    <button onClick={() => logout({ logoutParams: { returnTo: 'http://localhost:3000/' } })}>
      Log Out
    </button>
  );
};



export default function Home() {

  const { user, isAuthenticated, isLoading } = useAuth0();



  if (isLoading) {
    return <div>Loading ...</div>;
  }

  return (
    <>
      <Head>
        <title>Artyroom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <LoginButton />
          <LogoutButton />
        </div>
        <div>

          {isAuthenticated && user && (
            <div>
              <h1>Hello</h1>
              <img src={user.picture} alt={user.name} />
              <h2>{user.name}</h2>
              <p>{user.email}</p>
            </div>
          )}

        </div>
      </main>
    </>
  )
}
